# Generated by Django 5.0 on 2024-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0002_asignatura_administrador_estudiante_asignaturas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='rut',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
