# Generated by Django 5.0 on 2024-11-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0003_apoderado_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='rut',
        ),
    ]
