# Generated by Django 5.0 on 2024-11-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0005_apoderado_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
