# Generated by Django 5.0 on 2024-11-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, default=1, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor_principal',
        ),
        migrations.AddField(
            model_name='curso',
            name='asignaturas',
            field=models.ManyToManyField(related_name='cursos', to='App_Escolar.asignatura'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.CharField(choices=[('1-A', '1° Básico A'), ('2-A', '2° Básico A'), ('3-A', '3° Básico A'), ('4-A', '4° Básico A'), ('5-A', '5° Básico A'), ('6-A', '6° Básico A'), ('7-A', '7° Básico A'), ('8-A', '8° Básico A')], default='1-A', max_length=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='App_Escolar.profesorjefe'),
        ),
    ]
