# Generated by Django 5.0 on 2024-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0009_profesorjefe_remove_curso_profesor_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
