# Generated by Django 5.0 on 2024-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0010_alter_asignatura_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='limite_estudiantes',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
