# Generated by Django 5.0 on 2024-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0011_curso_limite_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='limite_estudiantes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
