# Generated by Django 5.0 on 2024-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0013_estudiante_curso_alter_curso_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='limite_estudiantes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
