# Generated by Django 5.0 on 2024-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0014_alter_curso_limite_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorjefe',
            name='grado_asignado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
