# Generated by Django 5.0 on 2024-11-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0015_profesorjefe_grado_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_asignados', to='App_Escolar.estudiante'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='limite_estudiantes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_asignados', to='App_Escolar.curso'),
        ),
    ]
