# Generated by Django 5.0 on 2024-11-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Escolar', '0016_curso_estudiantes_alter_curso_limite_estudiantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asociados', to='App_Escolar.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='profesores_asignados', to='App_Escolar.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_dirigidos', to='App_Escolar.profesorjefe'),
        ),
    ]
